### ISSUE TITLE
this package doesn't support on laravel 5.3 

### ISSUE THREAD

**Issue by ridwanskaterock** [marvinlabs/laravel-setup-wizard#5]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for marvinlabs/laravel-setup-wizard 0.2.0 -> satisfiable by marvinlabs/laravel-setup-wizard[0.2.0].
    - Conclusion: remove laravel/framework v5.3.29
    - Conclusion: don't install laravel/framework v5.3.29
    - marvinlabs/laravel-setup-wizard 0.2.0 requires illuminate/support 5.2.* -> satisfiable by illuminate/support[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - don't install illuminate/support v5.2.0|don't install laravel/framework v5.3.29
    - don't install illuminate/support v5.2.19|don't install laravel/framework v5.3.29
    - don't install illuminate/support v5.2.21|don't install laravel/framework v5.3.29
    - don't install illuminate/support v5.2.24|don't install laravel/framework v5.3.29
    - don't install illuminate/support v5.2.25|don't install laravel/framework v5.3.29
    - don't install illuminate/support v5.2.26|don't install laravel/framework v5.3.29
    - don't install illuminate/support v5.2.27|don't install laravel/framework v5.3.29
    - don't install illuminate/support v5.2.28|don't install laravel/framework v5.3.29
    - don't install illuminate/support v5.2.31|don't install laravel/framework v5.3.29
    - don't install illuminate/support v5.2.32|don't install laravel/framework v5.3.29
    - don't install illuminate/support v5.2.37|don't install laravel/framework v5.3.29
    - don't install illuminate/support v5.2.43|don't install laravel/framework v5.3.29
    - don't install illuminate/support v5.2.45|don't install laravel/framework v5.3.29
    - don't install illuminate/support v5.2.6|don't install laravel/framework v5.3.29
    - don't install illuminate/support v5.2.7|don't install laravel/framework v5.3.29
    - Installation request for laravel/framework (locked at v5.3.29, required as 5.3.*) -> satisfiable by laravel/framework[v5.3.29].

what tag version for laravel 5.3

thanks

**Comment by vpratfr** [comment]
0.2.1 supports it
